### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by ovesco**
This PR adds typescript types. They were developed in the context of a specific project but extended for the whole API.

## The `api` method
When calling `api`, each method's parameters is automatically infered. Example:
```ts
const eventRes = await connection.api([
  {
    method: 'events.getOne',
    params: {
      id: '...', // mandatory, will alert you if not set
      includeHistory: false,
    },
  },
]);
```

The problem is that the result is an array and Typescript, as far as I know, does not yet support indexed array access for types. As such, in the upper example, the eventRes is a best effort attempt at typing data.
```ts
// eventRes is an array
const data = eventRes[0];
if (xx.error) { /* deal with error */ }
else if (xx.event) { /* do something with event */ }
```

On the contrary, if you use the api method's `handleResult` parameter, result type will be correctly inferred.

## Pryv.Auth.setupAuth
This case was tricky as such types were handled this way:
```ts
import Pryv, { StateChange } from 'pryv';

await Pryv.Auth.setupAuth(
  {
    spanButtonID: 'pryv-button',
    onStateChange: (state) => {
      if (state.id === 'ACCEPTED') {
        const { apiEndpoint, username } =
          state as StateChange<'ACCEPTED'>; // No way to infer in the if directly
      }
    },
    authRequest: {
      // ...
    },
  },
  serviceInfoUrl
);
```

Please note that most of these types are based on reading the code and the documentation, without actual testing. As such I did the best I could to type response payload, but they might still hold small mistakes.

Best,
Guillaume

### CODE REVIEW

**Comment by perki** [comment]
Thanks a lot @ovesco !
We are going to review this quickly !

**Comment by sgoumaz** [comment]
Thanks for your patience and the contribution @ovesco, very much appreciated.
Before merging we want to include the type declarations in the `package.json` (`"types"` property); do you want to do it? (Otherwise we will.)

**Comment by ovesco** [comment]
Hello @sgoumaz it should now be okay

**Comment by sgoumaz** [comment]
Thanks very much @ovesco 🙏

**Pull request merged**
