### PR TITLE
Refactor/dev-env

### PR DESCRIPTION
**Pull request by sgoumaz**
See pryv/intranet#28

Left to do, before merge:
- [x] Probably rollback service info URL query string param name to `pryvServiceInfoUrl` (the `pryv` was removed as part of a series of renames but it makes sense to keep this one as it's likely to show up in customer apps).
- [x] See about cleaning up references in tests to `zouzou.com` and related, as it's an existing domain with no relevance whatsoever

After merge:
- [ ] Update [CodePen example](https://codepen.io/pryv/pen/ExVYemE) to be consistent with other examples (load from `api.pryv.com`, lowercase `pryv`, code style etc.)
- [ ] Publish version 2.3 (NPM & browser: remove obsolete `dist/demos/`, `dist/tests/`…)
- [ ] Public-archive obsolete repos (`…common`, `…socket.io`, `… monitor`) after updating their READMEs accordingly
- [ ] Review dev-site (+ others?) for possible needed updates

### CODE REVIEW

**Comment by sgoumaz** [comment]
So I ended up doing a bit more than just touching the dev environment. I'd be grateful if you can check the renames (mostly [this commit](https://github.com/pryv/lib-js/pull/52/commits/0917da4886d6507f2f51403bc9e63dc9ca5ad9c6)) and see whether it's likely to break something. I tried to be clean and deprecate while supporting the old names, but there might be a couple too many. 🙏

**Comment by sgoumaz** [comment]
@perki thx for checking the tests. I hadn't touched the implementation of them, only making sure nothing was (further) broken (so AFAIK all failures were already there on `master`).

**Comment by sgoumaz** [comment]
@perki Can we go ahead with the first two points in the PR description? Do you see other things to do before we merge?

**Comment by perki** [comment]
Hello @sgoumaz  
I reverted to pryvServiceInforUrl (only for query params) 
zouzou.com is now zou.zou 

Ready to merge

**Pull request merged**
